services:
  - type: web
    name: pvi-inspection-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
